services:
    sast:
        image: sast:latest
        build: .
        volumes:
            - .:/source/:ro
            - .:/output/:rw
        command: --scan-tool=kics,gosec,gitleaks

# docker compose build
# docker compose up -d
# docker compose logs -f
# docker compose down -v
