[versions]
latest = "+"
gradle = "8.4"
kotlin = "1.9.10"
ktlint = "11.6.0"
native = "0.9.27"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "latest" }

[bundles]

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
native = { id = "org.graalvm.buildtools.native", version.ref = "native" }
